from forge.classifier import classify

# Real AD5X header fields (from the TPU sandal sliced live 2026-06-27).
AD5X_HEADER = """; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2 on 2026-06-27 at 06:39:19
; total layer number: 9
; HEADER_BLOCK_END
; printer_model = Flashforge AD5X
; filament_type = TPU
; total filament used [g] = 26.40
; estimated printing time (normal mode) = 1h 44m 38s
"""


BAMBU_HEADER = """; printer_model = Bambu Lab A1
; filament_type = PLA
; filament: 1
; total filament used [g] = 12.00
; estimated printing time (normal mode) = 45m 0s
"""

ENDER_HEADER = """; printer_model = Creality Ender-3 Pro
; filament_type = PLA
; filament: 1
"""

KOBRA_HEADER = """; printer_model = Anycubic Kobra 3 Max 0.4 nozzle
; filament_type = PLA
; filament: 1
"""


# Real two-color AD5X encoding (from the red+blue sandal pair sliced live).
MULTI_HEADER = """; printer_model = Flashforge AD5X
; filament_type = TPU;TPU
; filament: 1,2
; filament_colour = #F72224;#2750E0
; enable_prime_tower = 1
; total filament used [g] = 68.26
; estimated printing time (normal mode) = 3h 02m 10s
"""


def test_ad5x_header_routes_to_ad5x():
    assert classify(AD5X_HEADER).printer == "ad5x"


def test_material_single():
    assert classify(AD5X_HEADER).material == "TPU"


def test_material_multicolor_dedupes_to_one_name():
    assert classify(MULTI_HEADER).material == "TPU"


def test_colors_defaults_to_one():
    assert classify(AD5X_HEADER).colors == 1


def test_colors_counts_multicolor():
    assert classify(MULTI_HEADER).colors == 2


def test_prime_tower_setting_is_machine_readable():
    assert classify(MULTI_HEADER).prime_tower_enabled is True
    assert classify("; enable_prime_tower = 0\n").prime_tower_enabled is False
    assert classify("; no tower setting\n").prime_tower_enabled is None


def test_est_seconds_parsed_h_m_s():
    assert classify(AD5X_HEADER).est_seconds == 1 * 3600 + 44 * 60 + 38


def test_est_seconds_parsed_m_s_only():
    assert classify(BAMBU_HEADER).est_seconds == 45 * 60


def test_est_grams_parsed():
    assert classify(AD5X_HEADER).est_grams == 26.40


def test_est_seconds_parses_days():
    # Real ankylosaurus estimate: "1d 11h 37m 11s" (caught the router under-reporting).
    h = "; estimated printing time (normal mode) = 1d 11h 37m 11s\n"
    assert classify(h).est_seconds == 86400 + 11 * 3600 + 37 * 60 + 11


def test_est_missing_is_none():
    assert classify(ENDER_HEADER).est_seconds is None
    assert classify(ENDER_HEADER).est_grams is None


def test_bambu_a2l_header_routes_to_bambu_a2l():
    h = "; printer_model = Bambu Lab A2L\n; filament_type = PLA\n"
    assert classify(h).printer == "bambu_a2l"


def test_bambu_p1s_header_routes_to_bambu_a2l():
    h = "; printer_model = Bambu Lab P1S\n; filament_type = PLA\n"
    assert classify(h).printer == "bambu_a2l"


def test_bambu_generic_header_routes_to_bambu():
    assert classify(BAMBU_HEADER).printer == "bambu"


def test_printer_settings_id_fallback_when_model_blank():
    h = (
        "; printer_model = \n"
        "; printer_settings_id = Ender3 Klipper (Foundry)\n"
        "; filament_type = PLA\n"
    )
    assert classify(h).printer == "ender"


def test_ender_header_routes_to_ender():
    assert classify(ENDER_HEADER).printer == "ender"


def test_kobra_header_routes_to_kobra3max_before_generic_klipper():
    assert classify(KOBRA_HEADER).printer == "kobra3max"


def test_kobra_settings_id_routes_to_kobra3max():
    h = "; printer_settings_id = Anycubic Kobra 3 Max 0.4 nozzle\n"
    assert classify(h).printer == "kobra3max"


def test_unknown_printer_model_routes_to_none():
    # Quarantine path: never guess a printer for an unrecognized model.
    assert classify("; printer_model = Prusa MK4\n").printer is None


def test_missing_header_routes_to_none():
    assert classify("G1 X0 Y0\n; no model here\n").printer is None
